name: Deploy Todo App to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'todo_app/**'
      - '.github/workflows/deploy_todo_app.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'todo_app/**'
      - '.github/workflows/deploy_todo_app.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true
      
      - name: Verify Flutter version
        run: flutter --version
      
      - name: Get dependencies
        working-directory: ./todo_app
        run: flutter pub get
      
      - name: Run tests
        working-directory: ./todo_app
        run: flutter test --no-pub
        continue-on-error: true
      
      - name: Build web app
        working-directory: ./todo_app
        run: |
          flutter build web \
            --release \
            --base-href "/ai_todo_app/" \
            --web-renderer canvaskit \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=/ai_todo_app/canvaskit/
      
      - name: Setup Pages
        if: github.event_name != 'pull_request'
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './todo_app/build/web'
  
  deploy:
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4